# # Obtener total clientes

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzQ2MDQ0NjUyLCJleHAiOjE3NDYwNDUyNTIsIm5iZiI6MTc0NjA0NDY1MiwianRpIjoiYmZpNWhwZURPTTZ3bm5GMCIsInN1YiI6IjEyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.J8P3E6_2eHmuCWXy8cTtnmvehCWQezWbkMqG0vFmAW0
GET http://127.0.0.1:8000/api/clients/total