PUT http://127.0.0.1:8000/api/clients/1
Content-Type: application/json
Accept: application/json
User-Agent: MyCustomUserAgent/1.0

{
    "first_name": "Clandestino",
    "last_name": "Smith",
    "email": "katherine.smith@example.org",
    "phone": "+9847584522",
    "address": "asfasf",
    "company_name": "Tech Solutions"
}
