POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzQzNTMzODMwLCJleHAiOjE3NDM1Mzc0MzAsIm5iZiI6MTc0MzUzMzgzMCwianRpIjoiSGY3ekZBRVh6aTJOcUhpdSIsInN1YiI6IjEyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.8fEDvi2Yd1pyJDC2fyddPUouvmlDOEn9xl4N316iRdE
