POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3JlZnJlc2giLCJpYXQiOjE3NDM3Njg1OTEsImV4cCI6MTc0Mzc3MjE5MSwibmJmIjoxNzQzNzY4NTkxLCJqdGkiOiIyVGthd09ZUWYwTUZ6Mm1EIiwic3ViIjoiMTQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.ZQqR2FIR1JjQNdyaoV0OCLMPc-0t1iXCrD_cOznZops
